name: .NET Standard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Standard
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.101
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore Deps
      run: dotnet restore cs/src/UtilPTT.sln
    - name: Build
      run: dotnet build cs/src/UtilPTT.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test cs/src/UtilPTT.sln --no-restore --verbosity normal

  build-macos:
    
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Standard
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: 3.1.101
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore Deps
        run: dotnet restore cs/src/UtilPTT.sln
      - name: Build
        run: dotnet build cs/src/UtilPTT.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test cs/src/UtilPTT.sln --no-restore --verbosity normal
